---
# tasks file for ansible-role-cuda
- name: "Gather OS specific variables"
  include_vars: "{{ item }}"
  with_first_found:
    - "{{ ansible_distribution|lower }}-{{ ansible_distribution_version }}.yml"
    - "{{ ansible_distribution|lower }}-{{ ansible_distribution_major_version }}.yml"
    - "{{ ansible_distribution|lower }}.yml"
    - "{{ ansible_os_family|lower }}.yml"

- include: yum_install.yml
  when:
    - ansible_pkg_mgr == 'yum'
    - gpu == True

- include: apt_install.yml
  when:
    - ansible_pkg_mgr == 'apt'
    - gpu == True

- include: cuda_init.yml
  when: cuda_init == True

- name: Template CUDA paths to user environments
  template:
    src: cuda.sh.j2
    dest: /etc/profile.d/cuda.sh
    mode: 0755
  when: cuda_bash_profile

# This is here because if we in the same playbook try to start slurmd without
# having run the cuda_init.sh script then slurmd doesn't start and the play fails.
- name: flush the handlers - so that the node is rebooted after CUDA is installed and that the GPUs are initialized before we start slurm
  meta: flush_handlers
