---
# tasks file for ansible-role-cuda
#
- name: add nvidia CUDA repo
  template: src=nvidia.repo.j2 dest=/etc/yum.repos.d/nvidia.repo owner=root group=root mode=0644 backup=yes

- name: install cuda software - this is slow
  yum: name={{ item }} state=present
  with_items: cuda_packages | default({})
  when: cuda_packages.0 != ""
  register: cuda_packages_installation

- name: restart machine if cuda was installed
  command: shutdown -r now "Ansible updates triggered"
  async: 0
  poll: 0
  ignore_errors: true
  when: cuda_packages_installation.changed and cuda_restart_node_on_install == True
  register: cuda_restart

- name: if restart, wait min 5s(+300s) for server to come back after reboot
  local_action: wait_for host={{ inventory_hostname }}
                port=22
                state=started
                delay=5
                timeout=300
  sudo: false
  when: cuda_restart.changed and cuda_restart_node_on_install == True

