---
# tasks file for ansible-role-cuda
#
- name: add nvidia CUDA repo
  template: src=nvidia.repo.j2 dest=/etc/yum.repos.d/nvidia.repo owner=root group=root mode=0644 backup=yes

- name: install cuda software - this is slow - restart if cuda_restart_node_on_install is True
  yum: name={{ item }} state=present
  with_items: "{{ cuda_packages | default({}) }}"
  when: cuda_packages.0 != ""
  register: cuda_packages_installation
  notify:
   - ZZ CUDA Restart server
   - ZZ CUDA Wait for server to restart

- name: template in cuda_init.sh used during boot
  template: src=cuda_init.sh.j2 
            dest=/usr/local/bin/cuda_init.sh 
            owner=root group=root mode=0755 
            backup=no
  when: cuda_init

- name: add the cuda_init.sh script to rc.local
  lineinfile: 
      dest=/etc/rc.local 
      insertafter=EOF 
      regexp="^/bin/bash /usr/local/bin/cuda_init.sh$"
      line="/bin/bash /usr/local/bin/cuda_init.sh" 
  when: cuda_init
