---

- name: ZZ CUDA Restart server
  command: shutdown -r now "Reboot triggered by Ansible"
  async: 0
  poll: 0
  ignore_errors: true
  when: cuda_packages_installation.changed and cuda_restart_node_on_install == True

- name: ZZ CUDA Wait for server to restart
  wait_for:
     host={{ inventory_hostname }}
     port=22
     delay=5
     timeout=300
  sudo: false
  when: cuda_restart.changed and cuda_restart_node_on_install == True
